name: "📚 Blog Updater"

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  update_blogs:
    name: "Update Blogs"
    runs-on: ubuntu-latest
    steps:
      - name: "📥  Fetching Repository Contents"
        uses: actions/checkout@main
      
      - name: "📚  Hashnode Updater"
        uses: "varunsridharan/action-hashnode-blog@main@1.2"
        with:
          USERNAME: "th3wall"
          COUNT: 5
          STYLE: "list"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
